services:
  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=useritau
      - MYSQL_PASSWORD=passworditau
      - MYSQL_DATABASE=itaudb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    expose:
      - "6379"
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/itaudb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis