openrouter:
  api:
    key: "sua-openrouter-api-key-bem-secreta"

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/itaudb?serverTimezone=UTC
    username: useritau
    password: passworditau
    driver-class-name: com.mysql.cj.jdbc.Driver
    output:
      ansi:
        enabled: always
  data:
    redis:
      host: redis
      port: 6379
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
logging:
  level:
    root: INFO
    com.coelho.desafio.itau: DEBUG