openrouter:
  api:
    key: "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"
    #key: "sk-41e7c86e37824666ae94ed5825dc31e3"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itaudb?serverTimezone=UTC
    username: useritau
    password: passworditau
    driver-class-name: com.mysql.cj.jdbc.Driver
    output:
      ansi:
        enabled: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

redis:
  host: localhost
  port: 6379